DROP TABLE IF EXISTS LOCAL;
DROP TABLE IF EXISTS CAMPUS;

CREATE TABLE CAMPUS(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    ADDRESS VARCHAR(255),
    PARKING_SPOTS INTEGER
);

CREATE TABLE LOCAL(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    TYPE VARCHAR(255),
    CAPACITY INTEGER,
    FLOOR INTEGER,
    CAMPUS_ID BIGINT,
    FOREIGN KEY(CAMPUS_ID) REFERENCES CAMPUS(ID)
);